/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>

namespace facebook {
namespace react {
class JSI_EXPORT NativeActionSheetManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeActionSheetManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void
  showActionSheetWithOptions(jsi::Runtime &rt, const jsi::Object &options, const jsi::Function &callback) = 0;
  virtual void showShareActionSheetWithOptions(
      jsi::Runtime &rt,
      const jsi::Object &options,
      const jsi::Function &failureCallback,
      const jsi::Function &successCallback) = 0;
};
class JSI_EXPORT NativeAlertManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeAlertManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void alertWithArgs(jsi::Runtime &rt, const jsi::Object &args, const jsi::Function &callback) = 0;
};
class JSI_EXPORT NativeAnimatedModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeAnimatedModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void startOperationBatch(jsi::Runtime &rt) = 0;
  virtual void finishOperationBatch(jsi::Runtime &rt) = 0;
  virtual void createAnimatedNode(jsi::Runtime &rt, double tag, const jsi::Object &config) = 0;
  virtual void getValue(jsi::Runtime &rt, double tag, const jsi::Function &saveValueCallback) = 0;
  virtual void startListeningToAnimatedNodeValue(jsi::Runtime &rt, double tag) = 0;
  virtual void stopListeningToAnimatedNodeValue(jsi::Runtime &rt, double tag) = 0;
  virtual void connectAnimatedNodes(jsi::Runtime &rt, double parentTag, double childTag) = 0;
  virtual void disconnectAnimatedNodes(jsi::Runtime &rt, double parentTag, double childTag) = 0;
  virtual void startAnimatingNode(
      jsi::Runtime &rt,
      double animationId,
      double nodeTag,
      const jsi::Object &config,
      const jsi::Function &endCallback) = 0;
  virtual void stopAnimation(jsi::Runtime &rt, double animationId) = 0;
  virtual void setAnimatedNodeValue(jsi::Runtime &rt, double nodeTag, double value) = 0;
  virtual void setAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag, double offset) = 0;
  virtual void flattenAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void extractAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void connectAnimatedNodeToView(jsi::Runtime &rt, double nodeTag, double viewTag) = 0;
  virtual void disconnectAnimatedNodeFromView(jsi::Runtime &rt, double nodeTag, double viewTag) = 0;
  virtual void restoreDefaultValues(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void dropAnimatedNode(jsi::Runtime &rt, double tag) = 0;
  virtual void addAnimatedEventToView(
      jsi::Runtime &rt,
      double viewTag,
      const jsi::String &eventName,
      const jsi::Object &eventMapping) = 0;
  virtual void removeAnimatedEventFromView(
      jsi::Runtime &rt,
      double viewTag,
      const jsi::String &eventName,
      double animatedNodeTag) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeAnimatedTurboModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeAnimatedTurboModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void startOperationBatch(jsi::Runtime &rt) = 0;
  virtual void finishOperationBatch(jsi::Runtime &rt) = 0;
  virtual void createAnimatedNode(jsi::Runtime &rt, double tag, const jsi::Object &config) = 0;
  virtual void getValue(jsi::Runtime &rt, double tag, const jsi::Function &saveValueCallback) = 0;
  virtual void startListeningToAnimatedNodeValue(jsi::Runtime &rt, double tag) = 0;
  virtual void stopListeningToAnimatedNodeValue(jsi::Runtime &rt, double tag) = 0;
  virtual void connectAnimatedNodes(jsi::Runtime &rt, double parentTag, double childTag) = 0;
  virtual void disconnectAnimatedNodes(jsi::Runtime &rt, double parentTag, double childTag) = 0;
  virtual void startAnimatingNode(
      jsi::Runtime &rt,
      double animationId,
      double nodeTag,
      const jsi::Object &config,
      const jsi::Function &endCallback) = 0;
  virtual void stopAnimation(jsi::Runtime &rt, double animationId) = 0;
  virtual void setAnimatedNodeValue(jsi::Runtime &rt, double nodeTag, double value) = 0;
  virtual void setAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag, double offset) = 0;
  virtual void flattenAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void extractAnimatedNodeOffset(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void connectAnimatedNodeToView(jsi::Runtime &rt, double nodeTag, double viewTag) = 0;
  virtual void disconnectAnimatedNodeFromView(jsi::Runtime &rt, double nodeTag, double viewTag) = 0;
  virtual void restoreDefaultValues(jsi::Runtime &rt, double nodeTag) = 0;
  virtual void dropAnimatedNode(jsi::Runtime &rt, double tag) = 0;
  virtual void addAnimatedEventToView(
      jsi::Runtime &rt,
      double viewTag,
      const jsi::String &eventName,
      const jsi::Object &eventMapping) = 0;
  virtual void removeAnimatedEventFromView(
      jsi::Runtime &rt,
      double viewTag,
      const jsi::String &eventName,
      double animatedNodeTag) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeAppStateCxxSpecJSI : public TurboModule {
 protected:
  NativeAppStateCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void getCurrentAppState(jsi::Runtime &rt, const jsi::Function &success, const jsi::Function &error) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeBlobModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeBlobModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void addNetworkingHandler(jsi::Runtime &rt) = 0;
  virtual void addWebSocketHandler(jsi::Runtime &rt, double id) = 0;
  virtual void removeWebSocketHandler(jsi::Runtime &rt, double id) = 0;
  virtual void sendOverSocket(jsi::Runtime &rt, const jsi::Object &blob, double socketID) = 0;
  virtual void createFromParts(jsi::Runtime &rt, const jsi::Array &parts, const jsi::String &withId) = 0;
  virtual void release(jsi::Runtime &rt, const jsi::String &blobId) = 0;
};
class JSI_EXPORT NativeFileReaderModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeFileReaderModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value readAsDataURL(jsi::Runtime &rt, const jsi::Object &data) = 0;
  virtual jsi::Value readAsText(jsi::Runtime &rt, const jsi::Object &data, const jsi::String &encoding) = 0;
};
class JSI_EXPORT NativeBugReportingCxxSpecJSI : public TurboModule {
 protected:
  NativeBugReportingCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void startReportAProblemFlow(jsi::Runtime &rt) = 0;
  virtual void setExtraData(jsi::Runtime &rt, const jsi::Object &extraData, const jsi::Object &extraFiles) = 0;
  virtual void setCategoryID(jsi::Runtime &rt, const jsi::String &categoryID) = 0;
};
class JSI_EXPORT NativeExceptionsManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeExceptionsManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  reportFatalException(jsi::Runtime &rt, const jsi::String &message, const jsi::Array &stack, double exceptionId) = 0;
  virtual void
  reportSoftException(jsi::Runtime &rt, const jsi::String &message, const jsi::Array &stack, double exceptionId) = 0;
  virtual void reportException(jsi::Runtime &rt, const jsi::Object &data) = 0;
  virtual void
  updateExceptionMessage(jsi::Runtime &rt, const jsi::String &message, const jsi::Array &stack, double exceptionId) = 0;
  virtual void dismissRedbox(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeJSCHeapCaptureCxxSpecJSI : public TurboModule {
 protected:
  NativeJSCHeapCaptureCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void captureComplete(jsi::Runtime &rt, const jsi::String &path, const jsi::String &error) = 0;
};
class JSI_EXPORT NativeImageEditorCxxSpecJSI : public TurboModule {
 protected:
  NativeImageEditorCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void cropImage(
      jsi::Runtime &rt,
      const jsi::String &uri,
      const jsi::Object &cropData,
      const jsi::Function &successCallback,
      const jsi::Function &errorCallback) = 0;
};
class JSI_EXPORT NativeImageLoaderAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeImageLoaderAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void abortRequest(jsi::Runtime &rt, double requestId) = 0;
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::Value getSize(jsi::Runtime &rt, const jsi::String &uri) = 0;
  virtual jsi::Value getSizeWithHeaders(jsi::Runtime &rt, const jsi::String &uri, const jsi::Object &headers) = 0;
  virtual jsi::Value prefetchImage(jsi::Runtime &rt, const jsi::String &uri, double requestId) = 0;
  virtual jsi::Value queryCache(jsi::Runtime &rt, const jsi::Array &uris) = 0;
};
class JSI_EXPORT NativeImageLoaderIOSCxxSpecJSI : public TurboModule {
 protected:
  NativeImageLoaderIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::Value getSize(jsi::Runtime &rt, const jsi::String &uri) = 0;
  virtual jsi::Value getSizeWithHeaders(jsi::Runtime &rt, const jsi::String &uri, const jsi::Object &headers) = 0;
  virtual jsi::Value prefetchImage(jsi::Runtime &rt, const jsi::String &uri) = 0;
  virtual jsi::Value prefetchImageWithMetadata(
      jsi::Runtime &rt,
      const jsi::String &uri,
      const jsi::String &queryRootName,
      double rootTag) = 0;
  virtual jsi::Value queryCache(jsi::Runtime &rt, const jsi::Array &uris) = 0;
};
class JSI_EXPORT NativeImagePickerIOSCxxSpecJSI : public TurboModule {
 protected:
  NativeImagePickerIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void canRecordVideos(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void canUseCamera(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void openCameraDialog(
      jsi::Runtime &rt,
      const jsi::Object &config,
      const jsi::Function &successCallback,
      const jsi::Function &cancelCallback) = 0;
  virtual void openSelectDialog(
      jsi::Runtime &rt,
      const jsi::Object &config,
      const jsi::Function &successCallback,
      const jsi::Function &cancelCallback) = 0;
  virtual void clearAllPendingVideos(jsi::Runtime &rt) = 0;
  virtual void removePendingVideo(jsi::Runtime &rt, const jsi::String &url) = 0;
};
class JSI_EXPORT NativeImageStoreAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeImageStoreAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void getBase64ForTag(
      jsi::Runtime &rt,
      const jsi::String &uri,
      const jsi::Function &successCallback,
      const jsi::Function &errorCallback) = 0;
};
class JSI_EXPORT NativeImageStoreIOSCxxSpecJSI : public TurboModule {
 protected:
  NativeImageStoreIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void getBase64ForTag(
      jsi::Runtime &rt,
      const jsi::String &uri,
      const jsi::Function &successCallback,
      const jsi::Function &errorCallback) = 0;
  virtual void hasImageForTag(jsi::Runtime &rt, const jsi::String &uri, const jsi::Function &callback) = 0;
  virtual void removeImageForTag(jsi::Runtime &rt, const jsi::String &uri) = 0;
  virtual void addImageFromBase64(
      jsi::Runtime &rt,
      const jsi::String &base64ImageData,
      const jsi::Function &successCallback,
      const jsi::Function &errorCallback) = 0;
};
class JSI_EXPORT NativeFrameRateLoggerCxxSpecJSI : public TurboModule {
 protected:
  NativeFrameRateLoggerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void setGlobalOptions(jsi::Runtime &rt, const jsi::Object &options) = 0;
  virtual void setContext(jsi::Runtime &rt, const jsi::String &context) = 0;
  virtual void beginScroll(jsi::Runtime &rt) = 0;
  virtual void endScroll(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeIntentAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeIntentAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value getInitialURL(jsi::Runtime &rt) = 0;
  virtual jsi::Value canOpenURL(jsi::Runtime &rt, const jsi::String &url) = 0;
  virtual jsi::Value openURL(jsi::Runtime &rt, const jsi::String &url) = 0;
  virtual jsi::Value openSettings(jsi::Runtime &rt) = 0;
  virtual jsi::Value sendIntent(jsi::Runtime &rt, const jsi::String &action, const jsi::Array &extras) = 0;
};
class JSI_EXPORT NativeLinkingManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeLinkingManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value getInitialURL(jsi::Runtime &rt) = 0;
  virtual jsi::Value canOpenURL(jsi::Runtime &rt, const jsi::String &url) = 0;
  virtual jsi::Value openURL(jsi::Runtime &rt, const jsi::String &url) = 0;
  virtual jsi::Value openSettings(jsi::Runtime &rt) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeModalManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeModalManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeNetworkingAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeNetworkingAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void sendRequest(
      jsi::Runtime &rt,
      const jsi::String &method,
      const jsi::String &url,
      double requestId,
      const jsi::Array &headers,
      const jsi::Object &data,
      const jsi::String &responseType,
      bool useIncrementalUpdates,
      double timeout,
      bool withCredentials) = 0;
  virtual void abortRequest(jsi::Runtime &rt, double requestId) = 0;
  virtual void clearCookies(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeNetworkingIOSCxxSpecJSI : public TurboModule {
 protected:
  NativeNetworkingIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void sendRequest(jsi::Runtime &rt, const jsi::Object &query, const jsi::Function &callback) = 0;
  virtual void abortRequest(jsi::Runtime &rt, double requestId) = 0;
  virtual void clearCookies(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeJSCSamplingProfilerCxxSpecJSI : public TurboModule {
 protected:
  NativeJSCSamplingProfilerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  operationComplete(jsi::Runtime &rt, double token, const jsi::String &result, const jsi::String &error) = 0;
};
class JSI_EXPORT NativePermissionsAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativePermissionsAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value checkPermission(jsi::Runtime &rt, const jsi::String &permission) = 0;
  virtual jsi::Value requestPermission(jsi::Runtime &rt, const jsi::String &permission) = 0;
  virtual jsi::Value shouldShowRequestPermissionRationale(jsi::Runtime &rt, const jsi::String &permission) = 0;
  virtual jsi::Value requestMultiplePermissions(jsi::Runtime &rt, const jsi::Array &permissions) = 0;
};
class JSI_EXPORT NativePushNotificationManagerIOSCxxSpecJSI : public TurboModule {
 protected:
  NativePushNotificationManagerIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void
  onFinishRemoteNotification(jsi::Runtime &rt, const jsi::String &notificationId, const jsi::String &fetchResult) = 0;
  virtual void setApplicationIconBadgeNumber(jsi::Runtime &rt, double num) = 0;
  virtual void getApplicationIconBadgeNumber(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual jsi::Value requestPermissions(jsi::Runtime &rt, const jsi::Object &permission) = 0;
  virtual void abandonPermissions(jsi::Runtime &rt) = 0;
  virtual void checkPermissions(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void presentLocalNotification(jsi::Runtime &rt, const jsi::Object &notification) = 0;
  virtual void scheduleLocalNotification(jsi::Runtime &rt, const jsi::Object &notification) = 0;
  virtual void cancelAllLocalNotifications(jsi::Runtime &rt) = 0;
  virtual void cancelLocalNotifications(jsi::Runtime &rt, const jsi::Object &userInfo) = 0;
  virtual jsi::Value getInitialNotification(jsi::Runtime &rt) = 0;
  virtual void getScheduledLocalNotifications(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void removeAllDeliveredNotifications(jsi::Runtime &rt) = 0;
  virtual void removeDeliveredNotifications(jsi::Runtime &rt, const jsi::Array &identifiers) = 0;
  virtual void getDeliveredNotifications(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventType) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeHeadlessJsTaskSupportCxxSpecJSI : public TurboModule {
 protected:
  NativeHeadlessJsTaskSupportCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void notifyTaskFinished(jsi::Runtime &rt, double taskId) = 0;
  virtual jsi::Value notifyTaskRetry(jsi::Runtime &rt, double taskId) = 0;
};
class JSI_EXPORT NativeI18nManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeI18nManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void allowRTL(jsi::Runtime &rt, bool allowRTL) = 0;
  virtual void forceRTL(jsi::Runtime &rt, bool forceRTL) = 0;
  virtual void swapLeftAndRightInRTL(jsi::Runtime &rt, bool flipStyles) = 0;
};
class JSI_EXPORT NativeUIManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeUIManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::Object getConstantsForViewManager(jsi::Runtime &rt, const jsi::String &viewManagerName) = 0;
  virtual jsi::Array getDefaultEventTypes(jsi::Runtime &rt) = 0;
  virtual jsi::Object lazilyLoadView(jsi::Runtime &rt, const jsi::String &name) = 0;
  virtual void createView(
      jsi::Runtime &rt,
      double reactTag,
      const jsi::String &viewName,
      double rootTag,
      const jsi::Object &props) = 0;
  virtual void updateView(jsi::Runtime &rt, double reactTag, const jsi::String &viewName, const jsi::Object &props) = 0;
  virtual void focus(jsi::Runtime &rt, double reactTag) = 0;
  virtual void blur(jsi::Runtime &rt, double reactTag) = 0;
  virtual void
  findSubviewIn(jsi::Runtime &rt, double reactTag, const jsi::Array &point, const jsi::Function &callback) = 0;
  virtual void
  dispatchViewManagerCommand(jsi::Runtime &rt, double reactTag, double commandID, const jsi::Array &commandArgs) = 0;
  virtual void measure(jsi::Runtime &rt, double reactTag, const jsi::Function &callback) = 0;
  virtual void measureInWindow(jsi::Runtime &rt, double reactTag, const jsi::Function &callback) = 0;
  virtual void
  viewIsDescendantOf(jsi::Runtime &rt, double reactTag, double ancestorReactTag, const jsi::Function &callback) = 0;
  virtual void measureLayout(
      jsi::Runtime &rt,
      double reactTag,
      double ancestorReactTag,
      const jsi::Function &errorCallback,
      const jsi::Function &callback) = 0;
  virtual void measureLayoutRelativeToParent(
      jsi::Runtime &rt,
      double reactTag,
      const jsi::Function &errorCallback,
      const jsi::Function &callback) = 0;
  virtual void setJSResponder(jsi::Runtime &rt, double reactTag, bool blockNativeResponder) = 0;
  virtual void clearJSResponder(jsi::Runtime &rt) = 0;
  virtual void configureNextLayoutAnimation(
      jsi::Runtime &rt,
      const jsi::Object &config,
      const jsi::Function &callback,
      const jsi::Function &errorCallback) = 0;
  virtual void removeSubviewsFromContainerWithID(jsi::Runtime &rt, double containerID) = 0;
  virtual void replaceExistingNonRootView(jsi::Runtime &rt, double reactTag, double newReactTag) = 0;
  virtual void setChildren(jsi::Runtime &rt, double containerTag, const jsi::Array &reactTags) = 0;
  virtual void manageChildren(
      jsi::Runtime &rt,
      double containerTag,
      const jsi::Array &moveFromIndices,
      const jsi::Array &moveToIndices,
      const jsi::Array &addChildReactTags,
      const jsi::Array &addAtIndices,
      const jsi::Array &removeAtIndices) = 0;
  virtual void setLayoutAnimationEnabledExperimental(jsi::Runtime &rt, bool enabled) = 0;
  virtual void sendAccessibilityEvent(jsi::Runtime &rt, double reactTag, double eventType) = 0;
  virtual void showPopupMenu(
      jsi::Runtime &rt,
      double reactTag,
      const jsi::Array &items,
      const jsi::Function &error,
      const jsi::Function &success) = 0;
  virtual void dismissPopupMenu(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeSettingsManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeSettingsManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void setValues(jsi::Runtime &rt, const jsi::Object &values) = 0;
  virtual void deleteValues(jsi::Runtime &rt, const jsi::Array &values) = 0;
};
class JSI_EXPORT NativeShareModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeShareModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::Value share(jsi::Runtime &rt, const jsi::Object &content, const jsi::String &dialogTitle) = 0;
};
class JSI_EXPORT NativeAsyncLocalStorageCxxSpecJSI : public TurboModule {
 protected:
  NativeAsyncLocalStorageCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void multiGet(jsi::Runtime &rt, const jsi::Array &keys, const jsi::Function &callback) = 0;
  virtual void multiSet(jsi::Runtime &rt, const jsi::Array &kvPairs, const jsi::Function &callback) = 0;
  virtual void multiMerge(jsi::Runtime &rt, const jsi::Array &kvPairs, const jsi::Function &callback) = 0;
  virtual void multiRemove(jsi::Runtime &rt, const jsi::Array &keys, const jsi::Function &callback) = 0;
  virtual void clear(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void getAllKeys(jsi::Runtime &rt, const jsi::Function &callback) = 0;
};
class JSI_EXPORT NativeAsyncSQLiteDBStorageCxxSpecJSI : public TurboModule {
 protected:
  NativeAsyncSQLiteDBStorageCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void multiGet(jsi::Runtime &rt, const jsi::Array &keys, const jsi::Function &callback) = 0;
  virtual void multiSet(jsi::Runtime &rt, const jsi::Array &kvPairs, const jsi::Function &callback) = 0;
  virtual void multiMerge(jsi::Runtime &rt, const jsi::Array &kvPairs, const jsi::Function &callback) = 0;
  virtual void multiRemove(jsi::Runtime &rt, const jsi::Array &keys, const jsi::Function &callback) = 0;
  virtual void clear(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void getAllKeys(jsi::Runtime &rt, const jsi::Function &callback) = 0;
};
class JSI_EXPORT NativeAppearanceCxxSpecJSI : public TurboModule {
 protected:
  NativeAppearanceCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::String getColorScheme(jsi::Runtime &rt) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeDeviceInfoCxxSpecJSI : public TurboModule {
 protected:
  NativeDeviceInfoCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeDevLoadingViewCxxSpecJSI : public TurboModule {
 protected:
  NativeDevLoadingViewCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  showMessage(jsi::Runtime &rt, const jsi::String &message, double withColor, double withBackgroundColor) = 0;
  virtual void hide(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeDevSplitBundleLoaderCxxSpecJSI : public TurboModule {
 protected:
  NativeDevSplitBundleLoaderCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value loadBundle(jsi::Runtime &rt, const jsi::String &bundlePath) = 0;
};
class JSI_EXPORT NativeJSDevSupportCxxSpecJSI : public TurboModule {
 protected:
  NativeJSDevSupportCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void onSuccess(jsi::Runtime &rt, const jsi::String &data) = 0;
  virtual void onFailure(jsi::Runtime &rt, double errorCode, const jsi::String &error) = 0;
};
class JSI_EXPORT NativePlatformConstantsAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativePlatformConstantsAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::String getAndroidID(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativePlatformConstantsIOSCxxSpecJSI : public TurboModule {
 protected:
  NativePlatformConstantsIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativePlatformConstantsWinCxxSpecJSI : public TurboModule {
 protected:
  NativePlatformConstantsWinCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeVibrationCxxSpecJSI : public TurboModule {
 protected:
  NativeVibrationCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void vibrate(jsi::Runtime &rt, double pattern) = 0;
  virtual void vibrateByPattern(jsi::Runtime &rt, const jsi::Array &pattern, double repeat) = 0;
  virtual void cancel(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeWebSocketModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeWebSocketModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void connect(
      jsi::Runtime &rt,
      const jsi::String &url,
      const jsi::Array &protocols,
      const jsi::Object &options,
      double socketID) = 0;
  virtual void send(jsi::Runtime &rt, const jsi::String &message, double forSocketID) = 0;
  virtual void sendBinary(jsi::Runtime &rt, const jsi::String &base64String, double forSocketID) = 0;
  virtual void ping(jsi::Runtime &rt, double socketID) = 0;
  virtual void close(jsi::Runtime &rt, double code, const jsi::String &reason, double socketID) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeAccessibilityInfoCxxSpecJSI : public TurboModule {
 protected:
  NativeAccessibilityInfoCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void isReduceMotionEnabled(jsi::Runtime &rt, const jsi::Function &onSuccess) = 0;
  virtual void isTouchExplorationEnabled(jsi::Runtime &rt, const jsi::Function &onSuccess) = 0;
  virtual void setAccessibilityFocus(jsi::Runtime &rt, double reactTag) = 0;
  virtual void announceForAccessibility(jsi::Runtime &rt, const jsi::String &announcement) = 0;
};
class JSI_EXPORT NativeAccessibilityManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeAccessibilityManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  getCurrentBoldTextState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void
  getCurrentGrayscaleState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void
  getCurrentInvertColorsState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void
  getCurrentReduceMotionState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void
  getCurrentReduceTransparencyState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void
  getCurrentVoiceOverState(jsi::Runtime &rt, const jsi::Function &onSuccess, const jsi::Function &onError) = 0;
  virtual void setAccessibilityContentSizeMultipliers(jsi::Runtime &rt, const jsi::Object &JSMultipliers) = 0;
  virtual void setAccessibilityFocus(jsi::Runtime &rt, double reactTag) = 0;
  virtual void announceForAccessibility(jsi::Runtime &rt, const jsi::String &announcement) = 0;
};
class JSI_EXPORT NativeClipboardCxxSpecJSI : public TurboModule {
 protected:
  NativeClipboardCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual jsi::Value getString(jsi::Runtime &rt) = 0;
  virtual void setString(jsi::Runtime &rt, const jsi::String &content) = 0;
};
class JSI_EXPORT NativeDatePickerAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeDatePickerAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Value open(jsi::Runtime &rt, const jsi::Object &options) = 0;
};
class JSI_EXPORT NativeKeyboardObserverCxxSpecJSI : public TurboModule {
 protected:
  NativeKeyboardObserverCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
};
class JSI_EXPORT NativeSoundManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeSoundManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void playTouchSound(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeStatusBarManagerAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeStatusBarManagerAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void setColor(jsi::Runtime &rt, double color, bool animated) = 0;
  virtual void setTranslucent(jsi::Runtime &rt, bool translucent) = 0;
  virtual void setStyle(jsi::Runtime &rt, const jsi::String &statusBarStyle) = 0;
  virtual void setHidden(jsi::Runtime &rt, bool hidden) = 0;
};
class JSI_EXPORT NativeStatusBarManagerIOSCxxSpecJSI : public TurboModule {
 protected:
  NativeStatusBarManagerIOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void getHeight(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual void setNetworkActivityIndicatorVisible(jsi::Runtime &rt, bool visible) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventType) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
  virtual void setStyle(jsi::Runtime &rt, const jsi::String &statusBarStyle, bool animated) = 0;
  virtual void setHidden(jsi::Runtime &rt, bool hidden, const jsi::String &withAnimation) = 0;
};
class JSI_EXPORT NativeToastAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeToastAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void show(jsi::Runtime &rt, const jsi::String &message, double duration) = 0;
  virtual void showWithGravity(jsi::Runtime &rt, const jsi::String &message, double duration, double gravity) = 0;
  virtual void showWithGravityAndOffset(
      jsi::Runtime &rt,
      const jsi::String &message,
      double duration,
      double gravity,
      double xOffset,
      double yOffset) = 0;
};
class JSI_EXPORT NativeSegmentFetcherCxxSpecJSI : public TurboModule {
 protected:
  NativeSegmentFetcherCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  fetchSegment(jsi::Runtime &rt, double segmentId, const jsi::Object &options, const jsi::Function &callback) = 0;
  virtual void
  getSegment(jsi::Runtime &rt, double segmentId, const jsi::Object &options, const jsi::Function &callback) = 0;
};
class JSI_EXPORT NativeTimingCxxSpecJSI : public TurboModule {
 protected:
  NativeTimingCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void
  createTimer(jsi::Runtime &rt, double callbackID, double duration, double jsSchedulingTime, bool repeats) = 0;
  virtual void deleteTimer(jsi::Runtime &rt, double timerID) = 0;
  virtual void setSendIdleEvents(jsi::Runtime &rt, bool sendIdleEvents) = 0;
};
class JSI_EXPORT NativeAnimationsDebugModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeAnimationsDebugModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void startRecordingFps(jsi::Runtime &rt) = 0;
  virtual void stopRecordingFps(jsi::Runtime &rt, double animationStopTimeMs) = 0;
};
class JSI_EXPORT NativeDeviceEventManagerCxxSpecJSI : public TurboModule {
 protected:
  NativeDeviceEventManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void invokeDefaultBackPressHandler(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeDevMenuCxxSpecJSI : public TurboModule {
 protected:
  NativeDevMenuCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void show(jsi::Runtime &rt) = 0;
  virtual void reload(jsi::Runtime &rt) = 0;
  virtual void debugRemotely(jsi::Runtime &rt, bool enableDebug) = 0;
  virtual void setProfilingEnabled(jsi::Runtime &rt, bool enabled) = 0;
  virtual void setHotLoadingEnabled(jsi::Runtime &rt, bool enabled) = 0;
};
class JSI_EXPORT NativeDevSettingsCxxSpecJSI : public TurboModule {
 protected:
  NativeDevSettingsCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void reload(jsi::Runtime &rt) = 0;
  virtual void reloadWithReason(jsi::Runtime &rt, const jsi::String &reason) = 0;
  virtual void onFastRefresh(jsi::Runtime &rt) = 0;
  virtual void setHotLoadingEnabled(jsi::Runtime &rt, bool isHotLoadingEnabled) = 0;
  virtual void setIsDebuggingRemotely(jsi::Runtime &rt, bool isDebuggingRemotelyEnabled) = 0;
  virtual void setProfilingEnabled(jsi::Runtime &rt, bool isProfilingEnabled) = 0;
  virtual void toggleElementInspector(jsi::Runtime &rt) = 0;
  virtual void addMenuItem(jsi::Runtime &rt, const jsi::String &title) = 0;
  virtual void addListener(jsi::Runtime &rt, const jsi::String &eventName) = 0;
  virtual void removeListeners(jsi::Runtime &rt, double count) = 0;
  virtual void setIsShakeToShowDevMenuEnabled(jsi::Runtime &rt, bool enabled) = 0;
};
class JSI_EXPORT NativeDialogManagerAndroidCxxSpecJSI : public TurboModule {
 protected:
  NativeDialogManagerAndroidCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void showAlert(
      jsi::Runtime &rt,
      const jsi::Object &config,
      const jsi::Function &onError,
      const jsi::Function &onAction) = 0;
};
class JSI_EXPORT NativeLogBoxCxxSpecJSI : public TurboModule {
 protected:
  NativeLogBoxCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void show(jsi::Runtime &rt) = 0;
  virtual void hide(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeRedBoxCxxSpecJSI : public TurboModule {
 protected:
  NativeRedBoxCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual void setExtraData(jsi::Runtime &rt, const jsi::Object &extraData, const jsi::String &forIdentifier) = 0;
  virtual void dismiss(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeSourceCodeCxxSpecJSI : public TurboModule {
 protected:
  NativeSourceCodeCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
};
class JSI_EXPORT NativeSampleTurboModuleCxxSpecJSI : public TurboModule {
 protected:
  NativeSampleTurboModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

 public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual void voidFunc(jsi::Runtime &rt) = 0;
  virtual bool getBool(jsi::Runtime &rt, bool arg) = 0;
  virtual double getNumber(jsi::Runtime &rt, double arg) = 0;
  virtual jsi::String getString(jsi::Runtime &rt, const jsi::String &arg) = 0;
  virtual jsi::Array getArray(jsi::Runtime &rt, const jsi::Array &arg) = 0;
  virtual jsi::Object getObject(jsi::Runtime &rt, const jsi::Object &arg) = 0;
  virtual double getRootTag(jsi::Runtime &rt, double arg) = 0;
  virtual jsi::Object getValue(jsi::Runtime &rt, double x, const jsi::String &y, const jsi::Object &z) = 0;
  virtual void getValueWithCallback(jsi::Runtime &rt, const jsi::Function &callback) = 0;
  virtual jsi::Value getValueWithPromise(jsi::Runtime &rt, bool error) = 0;
};

} // namespace react
} // namespace facebook
