// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef PROJECT_ROOT_NAMESPACE
#define PROJECT_ROOT_NAMESPACE react.uwp
#endif

namespace PROJECT_ROOT_NAMESPACE
{
  [version(1)]
  struct AccessibilityAction {		
      String Name;
      String Label;
  };
}
