// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200316.3

#ifndef WINRT_DeviceInfo2_0_H
#define WINRT_DeviceInfo2_0_H
WINRT_EXPORT namespace winrt::DeviceInfo2
{
    struct IReactPackageProvider;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<DeviceInfo2::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<DeviceInfo2::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<DeviceInfo2::ReactPackageProvider> = L"DeviceInfo2.ReactPackageProvider";
    template <> inline constexpr auto& name_v<DeviceInfo2::IReactPackageProvider> = L"DeviceInfo2.IReactPackageProvider";
    template <> inline constexpr guid guid_v<DeviceInfo2::IReactPackageProvider>{ 0x2A574026,0x6B0D,0x5310,{ 0x9F,0x01,0x9B,0x35,0x4A,0x99,0xE6,0xC8 } };
    template <> struct default_interface<DeviceInfo2::ReactPackageProvider>{ using type = DeviceInfo2::IReactPackageProvider; };
    template <> struct abi<DeviceInfo2::IReactPackageProvider>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_DeviceInfo2_IReactPackageProvider
    {
    };
    template <> struct consume<DeviceInfo2::IReactPackageProvider>
    {
        template <typename D> using type = consume_DeviceInfo2_IReactPackageProvider<D>;
    };
}
#endif
