// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200316.3

#ifndef WINRT_DeviceInfo2_2_H
#define WINRT_DeviceInfo2_2_H
#include "winrt/impl/Microsoft.ReactNative.1.h"
#include "DeviceInfo2.1.h"
WINRT_EXPORT namespace winrt::DeviceInfo2
{
    struct __declspec(empty_bases) ReactPackageProvider : DeviceInfo2::IReactPackageProvider,
        impl::require<ReactPackageProvider, Microsoft::ReactNative::IReactPackageProvider>
    {
        ReactPackageProvider(std::nullptr_t) noexcept {}
        ReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : DeviceInfo2::IReactPackageProvider(ptr, take_ownership_from_abi) {}
        ReactPackageProvider();
    };
}
#endif
