// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200316.3

#ifndef WINRT_DeviceInfo2_1_H
#define WINRT_DeviceInfo2_1_H
#include "DeviceInfo2.0.h"
WINRT_EXPORT namespace winrt::DeviceInfo2
{
    struct __declspec(empty_bases) IReactPackageProvider :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
