// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_NativeUICtrl_1_H
#define WINRT_NativeUICtrl_1_H
#include "NativeUICtrl.0.h"
namespace winrt::NativeUICtrl
{
    struct __declspec(empty_bases) IReactPackageProvider :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
