// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200316.3

#ifndef WINRT_SampleLibraryCpp_1_H
#define WINRT_SampleLibraryCpp_1_H
#include "SampleLibraryCpp.0.h"
WINRT_EXPORT namespace winrt::SampleLibraryCpp
{
    struct __declspec(empty_bases) ICustomUserControlCpp :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICustomUserControlCpp>
    {
        ICustomUserControlCpp(std::nullptr_t = nullptr) noexcept {}
        ICustomUserControlCpp(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICustomUserControlCppStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICustomUserControlCppStatics>
    {
        ICustomUserControlCppStatics(std::nullptr_t = nullptr) noexcept {}
        ICustomUserControlCppStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IReactPackageProvider :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
