// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {
  enum JSValueReaderState {
    NullValue,
    ObjectBegin,
    ObjectEnd,
    ArrayBegin,
    ArrayEnd,
    StringValue,
    BooleanValue,
    Int64Value,
    DoubleValue,
    Error,
  };

  interface IJSValueReader {
    JSValueReaderState ReadNext();
    String GetPropertyName();
    String GetString();
    Boolean GetBoolean();
    Int64 GetInt64();
    Double GetDouble();
  };
} // namespace Microsoft.ReactNative.Bridge
