// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative {

  delegate IInspectable PropertyValueMaker();

  [webhosthidden] interface IPropertyBag {
    IInspectable Get(Int64 isolationKey, String propertyName);
    IInspectable GetOrCreate(
        Int64 isolationKey, String propertyName, PropertyValueMaker valueMaker);
    IInspectable Replace(
        Int64 isolationKey, String propertyName, IInspectable value);
  };
} // namespace Microsoft.ReactNative
