// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IReactOptions.idl";
import "IReactViewHost.idl";
import "IReactViewOptions.idl";
import "IReactInstance2.idl";

namespace Microsoft.ReactNative {

  interface IReactHost {
    IReactOptions Options {
      get;
    };

    IReactInstance2 Instance {
      get;
    };

    Windows.Foundation.IAsyncAction ReloadInstance();

    Windows.Foundation.IAsyncAction ReloadInstanceWithOptions(
        IReactOptions options);

    Windows.Foundation.IAsyncAction UnloadInstance();

    IReactViewHost MakeViewHost(IReactViewOptions viewOptions);

    Windows.Foundation.IAsyncOperation<IVectorView<IReactViewHost> > GetViewHostList();
  };

} // namespace Microsoft.ReactNative
