// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "IReactDispatcher.idl";
import "IReactPropertyBag.idl";

namespace Microsoft.ReactNative {

  [webhosthidden]
  void ReactNotificationHandler();

  [webhosthidden]
  interface IReactNotificationCenter
  {
    //IReactSubscription AddObserver(
    //  IReactPropertyName notificationName,
    //  Windows.Foundation.EventHandler<ReactNotification> handler);

    //void PostNotification(IReactPropertyName notificationName, Object sender, Object payload);
    Int32 this[Int32 index];
  }
} // namespace Microsoft.ReactNative
