// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative {

  interface IReactViewHost {
    void Foo();
  };

} // namespace Microsoft.ReactNative
