// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.ReactNative
{
  interface IJsiRuntime;

  delegate void JsiDataHandler(UInt8[] data);

  [webhosthidden]
  interface IJsiBuffer
  {
    UInt32 Size { get; };
    void GetData(JsiDataHandler handler);
  };

  enum JsiValueType
  {
    Undefined,
    Null,
    Boolean,
    Number,
    Symbol,
    String,
    Object,
  };

  [webhosthidden]
  struct JsiValueData
  {
    JsiValueType Kind;
    Double NumberValue;
  };

  [default_interface]
  runtimeclass JsiPointer
  {
  };

  [default_interface]
  runtimeclass JsiPreparedJavaScript
  {
  };

  delegate JsiValueData JsiHostFunction(IJsiRuntime runtime, JsiValueData thisValue, JsiPointer thisPtr,
    JsiValueData[] args, JsiPointer[] ptrArgs, out JsiPointer ptrResult);

  [webhosthidden]
  interface IJsiHostObject
  {
    JsiValueData GetProperty(IJsiRuntime runtime, JsiPointer name, out JsiPointer ptrResult);
    void SetProperty(IJsiRuntime runtime, JsiPointer name, JsiValueData value, JsiPointer ptrValue);
    IVectorView<JsiPointer> GetPropertyNames(IJsiRuntime runtime);
  };

  [webhosthidden]
  interface IJsiRuntime
  {
    JsiValueData EvaluateJavaScript(IJsiBuffer buffer, String sourceUrl, out JsiPointer ptrResult);
    JsiPreparedJavaScript PrepareJavaScript(IJsiBuffer buffer, String sourceUrl);
    JsiValueData EvaluatePreparedJavaScript(JsiPreparedJavaScript js, out JsiPointer ptrResult);
    JsiPointer Global { get; };
    String Description { get; };
    Boolean IsInspectable { get; };

    JsiPointer CloneSymbol(JsiPointer symbol);
    JsiPointer CloneString(JsiPointer str);
    JsiPointer CloneObject(JsiPointer obj);
    JsiPointer ClonePropertyNameId(JsiPointer propertyNameId);

    JsiPointer CreatePropertyNameIdFromAscii(UInt8[] ascii);
    JsiPointer CreatePropertyNameIdFromUtf8(UInt8[] utf8);
    JsiPointer CreatePropertyNameIdFromString(JsiPointer str);
    void PropertyNameIdToUtf8(JsiPointer propertyNameId, JsiDataHandler utf8Handler);
    Boolean ComparePropertyNameIds(JsiPointer left, JsiPointer right);

    void SymbolToUtf8(JsiPointer symbol, JsiDataHandler utf8Handler);

    JsiPointer CreateStringFromAscii(UInt8[] ascii);
    JsiPointer CreateStringFromUtf8(UInt8[] utf8);
    void StringToUtf8(JsiPointer str, JsiDataHandler utf8Handler);

    JsiValueData CreateValueFromJsonUtf8(UInt8[] json, out JsiPointer ptrResult);

    JsiPointer CreateObject();
    JsiPointer CreateObjectWithHostObject(IJsiHostObject hostObject);
    IJsiHostObject GetHostObject(JsiPointer obj);
    JsiHostFunction GetHostFunction(JsiPointer func);

    JsiValueData GetProperty(JsiPointer obj, JsiPointer propertyNameId, out JsiPointer ptrResult);
    JsiValueData GetPropertyWithString(JsiPointer obj, JsiPointer nameStr, out JsiPointer ptrResult);
    Boolean HasProperty(JsiPointer obj, JsiPointer propertyNameId);
    Boolean HasPropertyWithString(JsiPointer obj, JsiPointer nameStr);
    void SetProperty(JsiPointer obj, JsiPointer propertyNameId, JsiValueData value, JsiPointer ptrValue);
    void SetPropertyWithString(JsiPointer obj, JsiPointer nameStr, JsiValueData value, JsiPointer ptrValue);

    Boolean IsArray(JsiPointer obj);
    Boolean IsArrayBuffer(JsiPointer obj);
    Boolean IsFunction(JsiPointer obj);
    Boolean IsHostObject(JsiPointer obj);
    Boolean IsHostFunction(JsiPointer obj);
    JsiPointer GetPropertyNameArray(JsiPointer obj);

    JsiPointer CreateWeakObject(JsiPointer obj);
    JsiValueData LockWeakObject(JsiPointer weakObject, out JsiPointer obj);

    JsiPointer CreateArray(UInt32 size);
    UInt32 GetArraySize(JsiPointer arr);
    UInt32 GetArrayBufferSize(JsiPointer arrayBuffer);
    void ArrayBufferToUtf8(JsiPointer arrayBuffer, JsiDataHandler utf8Handler);
    JsiValueData GetValueAtIndex(JsiPointer arr, UInt32 index, out JsiPointer ptrResult);
    void SetValueAtIndex(JsiPointer arr, UInt32 index, JsiValueData value, JsiPointer ptrValue);

    JsiPointer CreateFunctionFromHostFunction(JsiPointer propNameId, UInt32 paramCount, JsiHostFunction hostFunc);
    JsiValueData Call(JsiPointer func, JsiValueData thisData, JsiPointer thisPtr, JsiValueData[] args, JsiPointer[] ptrArgs, out JsiPointer ptrResult);
    JsiValueData CallAsConstructor(
        JsiPointer func, JsiValueData[] args, JsiPointer[] ptrArgs, out JsiPointer ptrResult);

    UInt64 PushScope();
    void PopScope(UInt64 scopeState);

    Boolean SymbolStrictEquals(JsiPointer left, JsiPointer right);
    Boolean StringStrictEquals(JsiPointer left, JsiPointer right);
    Boolean ObjectStrictEquals(JsiPointer left, JsiPointer right);

    Boolean InstanceOf(JsiPointer obj, JsiPointer constructor);
  };
}
