// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.ReactNative.Bridge {
  interface IReactModule {
    Int64 GetImpl();
  };
} // namespace Microsoft.ReactNative.Bridge
